In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
## Define the vocabulary size
voc_size=10000

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5704, 3761, 9143, 2206],
 [5704, 3761, 9143, 324],
 [5704, 1552, 9143, 5293],
 [1264, 8802, 9157, 8794, 3435],
 [1264, 8802, 9157, 8794, 2323],
 [6902, 5704, 7822, 9143, 382],
 [5158, 3506, 3295, 8794]]

In [22]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [23]:
import numpy as np

In [24]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5704 3761 9143 2206]
 [   0    0    0    0 5704 3761 9143  324]
 [   0    0    0    0 5704 1552 9143 5293]
 [   0    0    0 1264 8802 9157 8794 3435]
 [   0    0    0 1264 8802 9157 8794 2323]
 [   0    0    0 6902 5704 7822 9143  382]
 [   0    0    0    0 5158 3506 3295 8794]]


In [25]:
## feature representation
dim=10

In [26]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[[-0.00859503,  0.02422542, -0.03187989,  0.03219429,
          0.04134703, -0.02601531,  0.02857444,  0.01697738,
          0.00816816,  0.04472427],
        [-0.00859503,  0.02422542, -0.03187989,  0.03219429,
          0.04134703, -0.02601531,  0.02857444,  0.01697738,
          0.00816816,  0.04472427],
        [-0.00859503,  0.02422542, -0.03187989,  0.03219429,
          0.04134703, -0.02601531,  0.02857444,  0.01697738,
          0.00816816,  0.04472427],
        [-0.00859503,  0.02422542, -0.03187989,  0.03219429,
          0.04134703, -0.02601531,  0.02857444,  0.01697738,
          0.00816816,  0.04472427],
        [-0.03807527, -0.02652842,  0.01316145,  0.04448709,
         -0.02263678, -0.04205906,  0.03585363,  0.02445013,
          0.02314484,  0.0075523 ],
        [-0.02620032, -0.03188672, -0.03559766,  0.01013373,
         -0.00080733,  0.00974303, -0.03570831,  0.02101784,
         -0.04783837,  0.03655294],
        [ 0.04800693,  0.01264372, -0.03419542,  0.0

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0, 5704, 3761, 9143, 2206])